#!/usr/bin/env python3
"""
Auto-generated code for: Create a simple hello world function in Python
Generated by Autonomous Coding Workflow
"""

def hello_world(name="World"):
    """Print a greeting message."""
    print(f"Hello, {name}!")
    return f"Hello, {name}!"

if __name__ == "__main__":
    hello_world()
